# config/packages/shopify.yaml
parameters:
    shopify.api_key: '%env(SHOPIFY_API_KEY)%'
    shopify.api_secret: '%env(SHOPIFY_API_SECRET)%'
    shopify.api_scopes: '%env(SHOPIFY_API_SCOPES)%'
    shopify.webhook_endpoint: '%env(WEBHOOK_ENDPOINT)%'