# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2dcbcbaed00dd0347757c099a75be933"
application_url = "https://localhost:8000"
embedded = true
name = "Manage eComm team on Slack"
handle = "test-app-7571"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders"

[auth]
redirect_urls = [ "https://localhost:8000" ]

[pos]
embedded = false

[build]
dev_store_url = "slack-managed.myshopify.com"
